### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by hamiltonbarnes** [renatoalencar/atom-vlc#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-vlc](https://github.com/renatoalencar/atom-vlc) package 0.2.2

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 0

```
At file:///opt/atom/resources/app/static/index.html:1

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /packages/atom-vlc/lib/vlc.coffee:34:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -4:39.1.0 atom-vlc:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-music 0.7.0 
atom-vlc 0.2.2 
atomify 0.6.0 
chestnut-light-atom-syntax 0.2.1 
hey-pane 1.0.0 
youtube-pane 2.0.0 
```

**Comment by renatoalencar** [comment]
Can you tell me your VLC version?

**Comment by renatoalencar** [comment]
No more responses

**Comment by Kurty00** [comment]
Having the same Problem with Kubuntu 18.10 and VLC 3.0.4 Vetinari (3.0.4-0-gf615db6332).


```SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/kurt/.atom/packages/atom-vlc/lib/vlc.coffee:34:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by renatoalencar** [comment]
Sorry, but I'm actually maintaining this anymore. If you could debug this and find the reason of this, you can send a PR or more information so I can fix this. But I almost have no time to debug this right now.  Thanks for the feedback.
